### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SMXaS** [kvarcas91/global#3]
--module-path "C:\javafx-sdk-11.0.2\lib" --add-modules=javafx.controls,javafx.fxml,javafx.base,javafx.media,javafx.graphics,javafx.web

**Comment by AdamTakaacs** [comment]
https://github.com/joshnh/Git-Commands

the commands to push to the branch:
git add -A				Adds every change you want to push
git commit -m 'pushnote' 		Names the push 
git push -u origin "branch name"	Pushes to the selected branch
